CONFIG_LOG=y
CONFIG_ZMK_USB_LOGGING=y
CONFIG_ZMK_LOG_LEVEL_INF=y
CONFIG_LOG_BUFFER_SIZE=32768
CONFIG_PAW3222_DIAG_FORCE_POLLING=y
CONFIG_PAW3222_DIAG_POLL_INTERVAL_MS=15
CONFIG_PAW3222_DIAG_DELAYED_REINIT=y
CONFIG_PAW3222_DIAG_REINIT_DELAY_MS=5000
