CONFIG_TORABO_TSUKI_LP_ISSUE3_DIAG=y
CONFIG_ZMK_LOG_LEVEL_DBG=y

CONFIG_PAW3222_DIAG_FORCE_POLLING=y
CONFIG_PAW3222_DIAG_POLL_INTERVAL_MS=15
CONFIG_PAW3222_DIAG_DELAYED_REINIT=y
CONFIG_PAW3222_DIAG_REINIT_DELAY_MS=5000
